server:
  port: 8430
  ssl:
    enabled: true
    key-store: classpath:cert/camellia.icu.pfx
    key-store-password: 9qsris09
    key-store-type: PKCS12
spring:
#  profiles:
#    active: dev
  application:
    name: userService
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #boot2.6版本以上
  cloud:
    nacos:
      discovery:
        server-addr: 47.243.243.202:8848
        username: nacos
        password: nacos528
        service: userService
        namespace: bb997ae9-99d6-44f9-9336-eff723ba5d03
        group: Intelligent_scheduling
  boot:
    admin:
      context-path: /admin # 配置Spring Boot Admin Server路径
      notify:
        pagerduty:
          client-url: https://localhost:8430/admin
  cache:
    type: redis
  #redis配置
  redis:
    host: 47.243.243.202
    port: 6379
    connect-timeout: 5000ms
    lettuce:
      pool:
        max-active: 8  #连接池最大连接数，默认是 8
        max-idle: 8  #连接池最大空闲连接数，默认是 8
        min-idle: 0 # 连接池最小空闲连接数，默认是 0
        max-wait: -1ms #连接池最大等待时间，默认是 -1ms，表示无限等待
#    defaultSerializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer


  #    password:


  #      config:
#        server-addr: 47.113.223.214:8848
#        file-extension: yml
#        namespace: bb997ae9-99d6-44f9-9336-eff723ba5d03
#        group: Intelligent_scheduling
#        prefix: userService

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.211.77:3307/Intelligent_scheduling?serverTimezone=UTC
    username: root
    password: ZIYAN_0729gsz
#
#Actuator配置
management:
  endpoint:
    shutdown:
      enabled: true # 开启端点
    health:
      show-details: always # 是否展示健康检查详情
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有端点

# http://localhost:8430/actuator/health

