server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.243.243.202:8848
        username: nacos
        password: nacos528
        namespace: bb997ae9-99d6-44f9-9336-eff723ba5d03
        group: Intelligent_scheduling
  boot:
    admin:
      context-path: /admin # 配置Spring Boot Admin Server路径
      notify:
        pagerduty:
          client-url: http://localhost:80/admin
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由
          lower-case-service-id: true
      route:
        filters:
           -StripPrefix=1

