#server:
#  port: 80
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:cert/camellia.icu.pfx
    key-store-password: 9qsris09
    key-store-type: PKCS12
#    key-alias: alias
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.108.211.77:8848
        username: nacos
        password: nacos
        namespace: bb997ae9-99d6-44f9-9336-eff723ba5d03
        group: Intelligent_scheduling
#  boot:
#    admin:
#      context-path: /admin # 配置Spring Boot Admin Server路径
#      notify:
#        pagerduty:
#          client-url: https://localhost:8443/admin
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由
          lower-case-service-id: true
      route:
        filters:
           -StripPrefix=1

