spring:
  application:
    name: orderService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.243.243.202:3306/Intelligent_scheduling?serverTimezone=UTC
    username: zhipai
    password: ASD_123zp
  boot:
    admin:
      context-path: /admin # 配置Spring Boot Admin Server路径
      notify:
        pagerduty:
          client-url: https://localhost:8432/admin
  cloud:
    nacos:
      discovery:
        server-addr: 47.243.243.202:8848
        username: nacos
        password: nacos528
        service: orderService
        namespace: bb997ae9-99d6-44f9-9336-eff723ba5d03
        group: Intelligent_scheduling



server:
  port: 9000
  ssl:
    enabled: true
    key-store: classpath:cert/camellia.icu.pfx
    key-store-password: 9qsris09
    key-store-type: PKCS12

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl