server:
  port: 8431
  ssl:
    enabled: true
    key-store: classpath:cert/camellia.icu.pfx
    key-store-password: 9qsris09
    key-store-type: PKCS12
spring:
  application:
    name: employeeService
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #boot2.6版本以上
  cloud:
    nacos:
      discovery:
        server-addr: 47.243.243.202:8848
        username: nacos
        password: nacos528
        service: employeeService
        namespace: bb997ae9-99d6-44f9-9336-eff723ba5d03
        group: Intelligent_scheduling
  boot:
    admin:
      context-path: /admin # 配置Spring Boot Admin Server路径
      notify:
        pagerduty:
          client-url: http://localhost:8431/admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.211.77:3306/Intelligent_scheduling?serverTimezone=UTC
    username: admin
    password: mysqladmin
  cache:
    type: redis
  #redis配置
  redis:
    host: 47.243.243.202
    port: 6379

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)