server:
  port: 8431
spring:
  application:
    name: employeeService
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.223.214:8848
        username: nacos
        password: nacos
  #        service: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.211.77:3306/Intelligent_scheduling?serverTimezone=UTC
    username: admin
    password: mysqladmin

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)